---
- hosts: all
  become: yes
  become_method: sudo

  tasks:
   - name: update cache
     apt: update_cache=yes

   - name: Install list of packages
     apt: name={{item}} state=installed
     with_items:
       - clang
       - g++
       - cmake
       - swig
       - doxygen
       - pkg-config
       - valgrind
       - libboost-tools-dev
       - libboost-all-dev
       - libssl-dev
       - libsasl2-dev
       - libuuid1
       - libxerces-c-dev
       - ruby-dev
       - uuid-dev
