FROM rpconmq/prepare:latest

ARG external_uid
ADD IaC/build /build
WORKDIR /build
RUN ansible-playbook -i "localhost", -c local playbook.yml

VOLUME /third_party /third_party
RUN cd /third_party/qpid-proton/build && make install
RUN cd /third_party/qpid-cpp/build && make install
