Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

#  config.vm.network "forwarded_port", guest: 80, host: 8080
#  config.vm.network "private_network", ip: "192.168.33.10"
#  config.vm.network "public_network"
#  config.vm.synced_folder "../", "/vagrant_data"

  config.vm.provider :virtualbox do |vb|
#    vb.gui = true
#    vb.customize ["modifyvm", :id, "--memory", "2048"]
#    vb.memory = "1024"
    vb.customize ["modifyvm", :id, "--cpus", "2"]   
  end  


  config.vm.provision :ansible do |ansible|
    ansible.playbook = "./ansible/playbook.yml"
  end

#  config.vm.provision "shell", inline: <<-SHELL
#    cd /vagrant/third_party/rabbitmq-c
#    mkdir build && cd build
#    cmake ..
#     sudo cmake --build . --target install
#    cd /vagrant/third_party/amqpcpp
#     make
#    clang++ -std=c++11 BlackPerformer.cpp -I/usr/include/ -ltbb -lpthread -lboost_system
#  SHELL

end
