Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

#  config.vm.network "forwarded_port", guest: 80, host: 8080
#  config.vm.network "private_network", ip: "192.168.33.10"
#  config.vm.network "public_network"
  config.vm.synced_folder "../third_party", "/third_party"

  config.vm.provider :virtualbox do |vb|
#    vb.gui = true
#    vb.customize ["modifyvm", :id, "--memory", "2048"]
#    vb.memory = "1024"
    vb.customize ["modifyvm", :id, "--cpus", "2"]   
  end  


  config.vm.provision :ansible do |ansible|
    ansible.playbook = "./ansible/playbook.yml"
  end

  config.vm.provision "shell", inline: <<-SHELL
    cd /third_party/rabbitmq-c
    rm -f build
    mkdir build 
    cd build
    cmake ..
    sudo cmake --build . --target install
    cd /third_party/amqpcpp
    make
  SHELL

end
