Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

#  config.vm.network "forwarded_port", guest: 80, host: 8080
#  config.vm.network "private_network", ip: "192.168.33.10"
#  config.vm.network "public_network"
  config.vm.synced_folder "../third_party", "/third_party"
  config.vm.synced_folder "../", "/RPConMQ"
  
  config.vm.provider :virtualbox do |vb|
#    vb.gui = true
#    vb.customize ["modifyvm", :id, "--memory", "2048"]
#    vb.memory = "1024"
    vb.customize ["modifyvm", :id, "--cpus", "2"]   
  end  


  config.vm.provision :ansible do |ansible|
    ansible.playbook = "./ansible/playbook.yml"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    cd /third_party/qpid-proton
    rm -f build
    mkdir build 
    cd build
    cmake ..
    make all
    sudo make install
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    sudo dd if=/dev/zero of=/swapfile1 bs=1024 count=5120000
    sudo chown root:root /swapfile1
    sudo chmod 0600 /swapfile1
    sudo mkswap /swapfile1
    sudo swapon /swapfile1  
  SHELL

#   if you do not provide enough memory you may run in internal compiler error
  config.vm.provision "shell", inline: <<-SHELL
    cd /third_party/qpid-cpp
    rm -f build
    mkdir build 
    cd build
    cmake ..
    make test
    make install
  SHELL

end
