#!/bin/bash

function create_qpid_proton {
   echo "create qpid proton"
   cd /third_party/qpid-proton
   rm -f build
   mkdir build
   cd build
   cmake ..
   make all
   make install
}

function create_qpid_cpp {
   echo "create qpid cpp"
   cd /third_party/qpid-cpp
   rm -f build
   mkdir build
   cd build
   cmake ..
   make all
#   make install
}

function create_build_image {
  echo "create build image"
  cd /rpconmq
  docker build -f Dockerfile_build -t rpconmq/build:latest .
}

create_qpid_proton
create_qpid_cpp
create_build_image
